name: lafa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  flutter_bloc: ^9.0.0
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.2.4
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  geolocator: ^13.0.2
  provider: ^6.0.5
  image_picker: ^1.1.2
  logger: ^2.5.0
  uuid: ^4.2.2
  lottie: ^3.3.0
  connectivity_plus: ^6.1.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  tflite: ^1.1.2
  url_launcher: ^6.3.1
  logging: ^1.0.2
  chewie: ^1.10.0
  flutter_local_notifications: ^18.0.1
  opencv_4: ^1.0.0
  ml_linalg: ^13.11.29
  tflite_flutter: ^0.11.0
  local_auth: ^2.3.0
  firebase_database: ^11.3.4
  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  json_annotation: ^4.8.1
  image: ^4.1.3
  path_provider: ^2.1.2
  archive: ^4.0.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^3.1.0
  mockito: ^5.4.2  # Changed from SDK to version number
  build_runner: ^2.4.8
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tflite_model/
    - assets/models/
    - assets/models/mobilenet_ssd.tflite
    - assets/models/labels.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LAS.png"

